name: Publish
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update version
        run: cat deno.json | jq '.version = "${{ github.event.release.tag_name }}"' > deno.json.tmp
      - name: Publish package
        run: npx jsr publish --dry-run --config deno.json.tmp --allow-dirty
